server:
  port: 12100
spring:
  application:
    name: ZUUL

eureka:
  client:
    service-url:
      defaultZone: http://localhost:12000/eureka
endpoints:
  routes:
    enabled: true
management:
  security:
    enabled: false

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 600000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
