server:
  port: 12100
  context-path: /api
spring:
  application:
    name: ZUUL

eureka:
  client:
    service-url:
      defaultZone: http://localhost:12000/eureka
endpoints:
  routes:
    enabled: true
management:
  security:
    enabled: false

zuul:
  host:
    socket-timeout-millis: 120000
    connect-timeout-millis: 120000
  routes:
    dataengine:
      path: /dataengine/**
#      转发至服务时，带上path
      stripPrefix: false
    riskengine:
      path: /riskengine/**
      stripPrefix: false
    merchant:
      path: /merchant/**
      stripPrefix: false

ribbon:
  #Ribbon允许最大连接数，即所有后端微服务实例请求并发数之和的最大值。
  MaxTotalConnections: 500
  #单个后端微服务实例能接收的最大请求并发数
  MaxConnectionsPerHost: 500
  ReadTimeout: 120000
  ConnectTimeout: 120000

hystrix:
  command:
    default:
      execution:
        timeout:
          enable: false
        isolation:
          thread:
            timeoutInMilliseconds: 120000
