server:
  port: 12100
spring:
  application:
    name: ZUUL

eureka:
  client:
    service-url:
      defaultZone: http://localhost:12000/eureka
endpoints:
  routes:
    enabled: true
management:
  security:
    enabled: false

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 600000

ribbon:
  #Ribbon允许最大连接数，即所有后端微服务实例请求并发数之和的最大值。
  MaxTotalConnections: 500
  #单个后端微服务实例能接收的最大请求并发数
  MaxConnectionsPerHost: 500
  ReadTimeout: 2000
  ConnectTimeout: 2000

hystrix:
  command:
    default:
      execution:
        timeout:
          enable: false
        isolation:
          thread:
            timeoutInMilliseconds: 60000
