server:
  port: 12220
spring:
  application:
    name: DATAENGINE
eureka:
  client:
    service-url:
      defaultZone: http://localhost:12000/eureka
feign:
  hystrix:
    enabled: true

ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000
  OkToRetryOnAllOperations: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000
